### ISSUE TITLE
Notification about payment

### ISSUE THREAD

**Issue by pavelthq** [webmasterlv/swedbank-spp#1]
This example repository doesn't contain notification handling ( bankside-backend ) about payment. 

Any examples for notification response parsing? Is there some things that must be checked or only status check is ok?

**Comment by webmasterlv** [comment]
Hello!
As I understood from Swedbank, the notifications are sent to the URL you provide them when signing up for the service, and data sent is the same as after normal payment redirect.

So in this case standard status check is ok (the example is in _response/index.php_ file).
If you find out that the data is different and status check doesn't work, let me know, I will look into this.

**Comment by pavelthq** [comment]
Yes, you right about url.

Data looks like this (changed sensitive info)

```
<?xml version="1.0" encoding="utf-8"?><Response version="2.0" AccountName="accName"><Event><Purchase DPGReferenceId="123456" TransactionId="044/123456"><PaymentMethod name="SW"><ReferenceId>123</ReferenceId><ResponseCode>1101</ResponseCode><ResponseDescription>APPROVED</ResponseDescription><ServiceType>LTV_BANK</ServiceType><VK_REC_ACC>LVXXHABA0XXXXXX</VK_REC_ACC><VK_REC_NAME>Company</VK_REC_NAME><VK_SND_ID>HP</VK_SND_ID><VK_SND_ACC>LVXXHABA0YYYYYYYYY</VK_SND_ACC><VK_SND_NAME>Payer Name</VK_SND_NAME><VK_MSG>Test payment</VK_MSG><VK_T_DATE>17.05.2016</VK_T_DATE><VK_LANG>RUS</VK_LANG></PaymentMethod><Status>AUTHORISED</Status><Amount CurrencyCode="978" Exponent="2">2</Amount><RiskResult><StatusCode>100</StatusCode><StatusDescription><![CDATA[No Risk]]></StatusDescription></RiskResult><RecommendedClientMessage><![CDATA[Your transaction has been processed successfully.]]></RecommendedClientMessage></Purchase></Event></Response>
```

Do it is ok to just test StatusCode->100?

**Comment by webmasterlv** [comment]
Give me some time to test this. Quite possibly status check from notification is already possible with this library. I will keep you updated.

**Comment by webmasterlv** [comment]
Yeah, i had missed the notification handling. Support is now added, please refer to documentation on how to use it.

**Comment by pavelthq** [comment]
@webmasterlv Thanks! Very usefull!
