### ISSUE TITLE
Card capture

### ISSUE THREAD

**Issue by Arijus** [webmasterlv/swedbank-spp#7]
Hi,
 could you please explain how to use card capture?
I see stage 1 requestCardCapture(), but what to do next?

More explanation:
I'm trying to do credit card capture in website. After that, pay with card without asking card details. And later if user wants, allpw schedule recurring.

**Comment by webmasterlv** [comment]
@Arijus Hi,
Yeah it's rather complicated. When I made this, I didn't have much time to plan everything more beautifully, however the process itself is very complicated in documentation. Maybe try official library if this is too much (never worked with it). Let me know if you need more clarification.

Anyway, first of all, if you just need to obtain card token without first payment, then (assuming you have your transactions table where you store transactions):

Intitialize gateway with capture response url (see step 1 - credentials in manual):

**Request 1.**

Create new order:
```
$id = 1232323; // Some unique transaction ID from your payments table
$merchant_reference = "INTERNALID/" . $id;
$order	 = new Order($merchant_reference, 'Subscription', 0); // Amount should be 0
```

Request card capture:
```
try {
    $result = $gateway -> requestCardCapture($order);
}
```
Save obtained reference to your order to be used later and redirect user to card page:
```
$reference = $result -> getReference();
$result -> getRedirectUrl()
```

**Request 2.**

In capture response URL (after returning from bank):
Get your transaction record by reference:
```
$reference = $_GET['dts_reference'];
```
Create recurring setup (initialize $gateway with another response URL for recurring setup, just like before):
```
try {
    $result = $gateway -> recurringSetup($order, $customer);
}
```
Now you have a subscription token. But you need to check is it completed yet.
```
$recurring_reference = $result['recurring_reference'];
$result = $result['result'];
$action = $result -> getNextAction();

if ($result -> isSuccess()) {
    if ($action['action'] == 'success') {
        // All is fine, card token is valid and can be used for payments
    }

    if ($action['action'] == 'post_redirect') {
        // 3DS setup required.
    }
}
```
If you require 3DS authentication, $action['form'] contains all fields you need to submit for 3DS authentication (there is `action` - URL where form should be pointed to and `fields` - hidden field name and value). I made a simple HTML form with fields from that array, and submitted it automatically upon page load.
In this form you should add also:
```
<input type="hidden" name="TermUrl" value="<?=$callback?>" />
<input type="hidden" name="MD" value="<?=$orderid?>" /> 
```
Where $callback is third response URL which will check 3DS result, and MD is your internal transaction ID.

There:

**Request 3.**
```
$orderid = $_POST['MD'];

$op = new Verify3DSecure($order, $reference); //$reference is the same you got after recurring setup.
$result = $gateway -> processOperation($op);
if ($result -> isSuccess()) {
    $action = $result -> getNextAction();
	
    if ($action['action'] == 'success') {
        // 3DS verification success, token can be used for payments
    }
}
```

**Comment by Arijus** [comment]
Thanks for help! 
Have another problem. Lets say i have captured card (masked number, expirity and token) in my database.
How i can make single time payment?
And recurring (every month) if user wants auto charge?

**Comment by Arijus** [comment]
I did like this:
**Created new method for gateway**
```
public function requestPaymentWithToken(Order $order, Customer $customer, \Payments\Entity\CreditCard $creditCard) {
	$result = $this->processOperation(new CreditCardSetup($order, $customer, $creditCard));
	$action = $result->getNextAction();

	if ($result->isSuccess()) {
		if ($action['action'] == '3ds_verify') {
			$auth_operation = new Auth3DSecure($result->getReference());
			$result = $this->processOperation($auth_operation);
		} elseif ($action['action'] == 'post_redirect') {
			return [
				'form' => $action['form'],
				'result' => $result,
			];
		}
	}

	return [
		'result' => $result,
	];
}
```
After this user gets redirect like before to auth (post_redirect with form)
And when user comes back, i check using this method:
```
public function verifyCardCapture3DSecure(Order $order, $reference) {
	$operation = new Verify3DSecure($order, $reference);
	$result = $this->processOperation($operation);
	return $result;
}
```
If result isSuccess() then its successfully charged card? Or i should do something more?

**Comment by webmasterlv** [comment]
@Arijus Hey, after you have obtained token, you charge card like this:

```php
$order = new Order('', 'Subscription', 4.99);
$result = $gateway -> processOperation(new RecurringPay($order, $recurring_reference));
```

There is possibility to make automatic payments (so that bank charges card, not your script), but I prefer this way. So you have more control over customer subscription.

**Comment by webmasterlv** [comment]
@Arijus 
If I understand your code, seems correct. If you have success after 3DS verify, it means that you can save recurring reference in your database and can use that token to charge card when you need it.

**Comment by Arijus** [comment]
@webmasterlv thank you very much! I will try this way. 
The point is that before this call, I have saved token to database. So using this way, i should replace $recurring_reference with that token right?
```
$order = new Order('', 'Subscription', 4.99);
$result = $gateway -> processOperation(new RecurringPay($order, $recurring_reference));
```

**Comment by webmasterlv** [comment]
@Arijus Hold on, I'll try to make more complete example

**Comment by webmasterlv** [comment]
@Arijus  Here is complete example. I commented out which token you should use for charge, so I think this will answer your question.

```php
use Swedbank\SPP\Accreditation;
use Swedbank\SPP\Gateway;
use Swedbank\SPP\Merchant;

class Payments extends Controller
{
    protected function getGateway($redirectUrl)
    {
        $client = '???'; // Your clientID from bank
        $pass = '???'; // Gateway pass

        $accreditation = new Accreditation();
        $accreditation -> setProd($client, $pass, $response_url);

        $merchant = new Merchant();
        $merchant -> setRegion(Gateway::REGION_LAT);
        $merchant -> setLanguage(Gateway::LANG_LAT);

        return new Gateway($accreditation, $merchant, Gateway::ENV_PROD);
    }

    public function captureStep1()
    {
        // This is where user starts

        // Add your validation code etc.

        // If you pass 0, then you will only get card token, and no charge from card will be made.
        // Of course you can pass non-zero value, in this case, the customer will be charged as well
        $amount = 0;
        
        $transaction = (new Transaction()) -> save([
            'status' => 'initiated',
            'amount' => $amount
            // Here you create record in your transactions table. You should have your internal
            // transaction ID so you can find your initiail transaction later on
        ]);

        // Replace with real absolute URL like route('payments.captureStep2'). 
        // Here and onwards is just name of the route
        $redirect = 'captureStep2';
        
        $gateway = $this -> getGateway($redirect);


        $merchant_reference = 'SUBS/' . $transaction -> id; // This can be random
        $order	 = new Order($merchant_reference, 'Subscription service', $amount);

        try {
                $result = $gateway -> requestCardCapture($order);
        } catch (\Exception $e) {
             $transaction -> save([
                 'status' => 'failed'
             ]);
            ​// Something is totally wrong...
            return false;
       }

        if ($result -> isSuccess()) {
            $transaction -> reference_id = $result -> getReference();
            $transaction -> save([
                'status' => 'started'
            ]);

            // Redirecting user to bank
            return redirect($result -> getRedirectUrl());
        }
    }
    
    public function captureStep2(Request $request)
    {
        $reference = $request -> get('dts_reference');
        
        // Now find your transaction reference
        $transaction = Transaction::where('reference_id', $reference) -> first();
        
        $merchRef = 'SUBS/'.$transaction -> id;
        $order	 = new Order($merchRef, 'Subscription service', $transaction -> amount);
        
        // Capture setup redirect
        $redirect = 'captureStep3';
        
        $gateway = $this -> getGateway($redirect);
        
        // Now you need customer. Fill as much as you can.
        $customer = Customer::fromArray([
            'email' => '',
            'first_name' => '',
            'last_name' => '',
            'city' => '',
            'phone' => '',
            'zip_code' => '',
            'address' => '',
            'country' => 'LV'
        ]);
		
        $recurring_reference = null;
		
        try {
            $result = $gateway -> recurringSetup($order, $customer);
        } catch (\Exception $e) {
            $transaction -> save([
                'status' => 'failed'
            ]);

	    // Fail. Check response
            return false;
        }
		
        $result = $result['result'];
		
        if ($result -> isSuccess()) {
            $transaction -> save([
                // THIS is the token with which you make charge from card
                'recurring_reference' => $result['recurring_reference'] 
            ]);
		    
            $action = $result -> getNextAction();
		    
            if ($action['action'] == 'success') {
                // You're done! Recurring reference can be used for charging.
                // Redirect user to success page.
                $transaction -> save([
                    'status' => 'success'
                ]);
            }
		    
            if ($action['action'] == 'post_redirect') {
                // Not there yet. 3DS required to obtain card token.
		        
                $transaction -> save([
                    'status' => '3dsverify'
                ]);
		        
                return view('3ds_form') -> with([
                    'redirect' => $redirect,
                    'action' => $action['form']['action'],
                    'fields' => $action['form']['fields'],
                    'transaction_id' => $transaction -> id
                ]);
            }
        } else {
            // Call was ok, but response was not. Anyway, here is the error.
            // Check response.
            $transaction -> save([
                'status' => 'failed'
            ]);
        }
    }
    
    public function captureStep3(Request $request)
    {
        // You should be here after users makes 3DS verification
        $transaction_id = $request > post('MD');
        
        $transaction = Transaction::where('id', $transaction_id) -> first();
        
        $order	 = new Order('SUBS/'.$transaction -> id, 'Subscription service', $transaction -> amount);
        
        // Important! Here second parameter is reference_id from step 2
        $operation = new Verify3DSecure($order, $transaction -> reference_id);
        
        // Here we are coming back to step 2
        $redirect = 'captureStep2';
        
        $gateway = $this -> getGateway($redirect);
	$result = $gateway -> processOperation($operation);
		
	if ($result -> isSuccess()) {
	    $action = $result -> getNextAction();
		    
	    if ($action['action'] == 'success') {
	        // You're done! Recurring reference can be used for charging.
	        // Redirect user to success page.
	        $transaction -> save([
                        'status' => 'success'
                    ]);
            } else {
	        // Fail. Check response
	        $transaction -> save([
                         'status' => 'failed'
                    ]);
            }
        } else {
            // Fail. Check response.
            $transaction -> save([
                'status' => 'failed'
            ]);
        }
    }
}
```

Here is 3DS form:

```html
<form name="form" id="form" action="{{$action}}" method="POST">
	<div>
		<h3>Uzgaidiet, notiek savienošanās ar maksājumu sistēmu...</h3>

		<p>
			Ja novirzīšana nenotiek automātiski, spiediet šo pogu:
			<button class="btn btn-primary">Turpināt</button>
		</p>
	</div>

	@foreach ($fields as $k => $v)
	    <input type="hidden" name="{{$k}}" value="{{$v}}" />
	@endforeach
	?>
	<input type="hidden" name="TermUrl" value="{{$redirect}}" />
	<input type="hidden" name="MD" value="{{$transaction_id}}" /> 
</form>

<script>
	document.getElementById('form').submit();
</script>

```

Here is console command to make charge from card:

```php
$order = new Order('', 'Subscription', 4.99);
$result = $gateway -> processOperation(new RecurringPay($order, $transaction -> recurring_reference));

```

**Comment by Arijus** [comment]
@webmasterlv Thank you for this great explanation!
Just want to double check. After this:

```
$order = new Order('', 'Subscription', 4.99);
$result = $gateway -> processOperation(new RecurringPay($order, $transaction -> recurring_reference));
```

Have to check response with $result->isSuccess() - and if TRUE it means that amount was successfully charged? 
Thanks a lot!

**Comment by webmasterlv** [comment]
@Arijus Sure. Because card can be expired, there can be insufficient funds, etc. Just check `$result -> isSuccess()` and depending on that, update customer subscribtion.

**Comment by Arijus** [comment]
@webmasterlv Strange, that var_dump returns this info for me, but isSuccess is true:
```
bool(true) <-- var_dump($result->isSuccess ());

object(Swedbank\SPP\Response\RecurringPayResponse)#6816 (1) {
  ["data":protected]=>
  array(14) {
    ["@attributes"]=>
    array(1) {
      ["version"]=>
      string(1) "2"
    }
    ["CardTxn"]=>
    array(4) {
      ["authcode"]=>
      string(6) "401266"
      ["card_scheme"]=>
      string(16) "Debit Mastercard"
      ["country"]=>
      string(14) "United Kingdom"
      ["token"]=>
      string(20) "Tokenization Failure"
    }
    ["ContAuthTxn"]=>
    array(1) {
      ["account_status"]=>
      string(66) "Using account ref 3000900031245494. CONT_AUTH transaction complete"
    }
    ["acquirer"]=>
    string(25) "Swedbank Baltic Lithuania"
    ["datacash_reference"]=>
    string(16) "3700900031245495"
    ["extended_response_message"]=>
    string(12) "Approved, OK"
    ["extended_status"]=>
    string(3) "000"
    ["information"]=>
    string(38) "Invalid value for field PAN in request" // <------ i dont like this one? :)
    ["merchantreference"]=>
    string(16) "ABO101/20/482841"
    ["mid"]=>
    string(10) "0009150916"
    ["mode"]=>
    string(4) "LIVE"
    ["reason"]=>
    string(8) "ACCEPTED"
    ["status"]=>
    string(1) "1"
    ["time"]=>
    string(10) "1619516138"
  }
}
```

**Comment by webmasterlv** [comment]
@Arijus Well that's strange, because status=1 and extended_status=000, which means success. Do you have access to DataCash control panel so you can check transaction there?

**Comment by raimkeri** [comment]
Hi,
Error or to be precise message:     "Invalid value for field PAN in request" can be ignored. It appears only in recurring transactions.

Most important is that Status is 1, which means it is successful.

Best regards,
Raimonds

**Comment by Arijus** [comment]
@webmasterlv i will ask for control panel logins. I hope they will send :)

@raimkeri okey, but for example i change in my database token with different number and try to do transaction, and i get status = 1. Thats little bit tricky.

**Comment by webmasterlv** [comment]
@raimkeri Thanks for explanation
@Arijus I can't see how that should work, it means Swedbank is accepting some random token for card payment?

**Comment by Arijus** [comment]
@webmasterlv maybe in test mode. 
For example i have token: 3000900031245494 <- REAL ONE
If i change it to **2**000900031245494, i get: TRUE
If i change it to 3000**8**00031245494, i get: FALSE: The number supplied failed to pass the luhn check.

**Comment by raimkeri** [comment]
Sorry what is the aim of changing token? Regardless of “luhn check” you will not be able to process non gataway generated tokens.

**Comment by Arijus** [comment]
@raimkeri Just wanted to be sure that $result->isSuccess() returns TRUE only when card is being charged.

**Comment by raimkeri** [comment]
I can answer regarding Gateway. Gateway will answer with status 1 only in case transaction is accepted. If you will send wrong token it will be rejected.

**Comment by Arijus** [comment]
@raimkeri Thank you!

**Comment by Arijus** [comment]
@webmasterlv I see that RecurringPay class with Maestro card returns "3-D Secure Required", so need to check 3DS even if i have token?
And RecurringPayResponse class do not have getNextAction method.

**Comment by Arijus** [comment]
Guys, maybe you know why on Chrome, most of the times when you come back from card confirm, session is gone? User is logged out. For firefox all good. After return URL returns 302 Found status.

**Comment by arnisjuraga** [comment]
At first, check the domain on which You are returning.
If You have your main site visiting on "https://site.com" but are returning to "https://www.site.com" it will drop session because of different domains. This is simple mistake to fix.

**Comment by Arijus** [comment]
> At first, check the domain on which You are returning.
> If You have your main site visiting on "https://site.com" but are returning to "https://www.site.com" it will drop session because of different domains. This is simple mistake to fix.

**Comment by Arijus** [comment]
I checked, but POST request url is good... And its strange, that this behavior comes from Chrome

**Comment by webmasterlv** [comment]
@Arijus check if your session cookie is set as SameSite=None (and also secure as a consequence)

**Comment by Arijus** [comment]
> @Arijus check if your session cookie is set as SameSite=None (and also secure as a consequence)

Thanks, that was the problem! :)

**Comment by Arijus** [comment]
I have one more problem after moving to production env. I can get token for autocharge, but when I try to do real payment, i get this error: HPS: Communications error. In DEV env its all good. Any ideas?

**Comment by webmasterlv** [comment]
@Arijus seems like network problem. do you have access to shell? if so, try to curl to https://mars.transaction.datacash.com/Transaction and see what happens.

**Comment by Arijus** [comment]
I have this response:
```
curl https://mars.transaction.datacash.com/Transaction
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <information>Parse XML failed -
syntax error at line 1, column 0, byte 0</information>
  <reason>Invalid XML</reason>
  <status>60</status>
</Response>
```

**Comment by Arijus** [comment]
It's strange, because I can do transactions for 0 eur (for authorization). But when I'm trying to charge with token - then I get this error.

**Comment by Arijus** [comment]
That problem was fixed by swedbank. But now I cant assign card to profile, but when doing payment, I get success, but money is not charged. Maybe someone had this issue?
